title: BeSecure Schema
description: Information about the schema definitions for BeSecure community projects.
theme: just-the-docs

url: https://just-the-docs.github.io


aux_links:
  "BeSecure Schema on GitHub":
    - https://github.com/harimohanr/bes-schema-site

logo: "/assets/Be-Secure-horizontal-grey.png"